# Generated by Django 4.1.5 on 2023-02-26 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farming_app', '0004_alter_retailer_model_confirmation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmercomplain_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 26, 10, 33, 48, 720792))),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('complaint_title', models.CharField(max_length=50)),
                ('complaint', models.TextField()),
                ('number', models.BigIntegerField()),
                ('state', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('confirmation', models.CharField(default='unread', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='retailer_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 26, 10, 33, 48, 719759)),
        ),
        migrations.AlterField(
            model_name='signup_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 26, 10, 33, 48, 719759)),
        ),
    ]
