# Generated by Django 4.1.5 on 2023-02-26 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farming_app', '0005_farmercomplain_model_alter_retailer_model_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmertips_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 26, 19, 13, 34, 979139))),
                ('subject', models.CharField(max_length=50)),
                ('tips', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='farmercomplain_model',
            name='confirmation',
            field=models.CharField(blank=True, default='unread', max_length=15),
        ),
        migrations.AlterField(
            model_name='farmercomplain_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 26, 19, 13, 34, 978141)),
        ),
        migrations.AlterField(
            model_name='retailer_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 26, 19, 13, 34, 978141)),
        ),
        migrations.AlterField(
            model_name='signup_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 26, 19, 13, 34, 978141)),
        ),
    ]
