# Generated by Django 4.1.5 on 2023-02-27 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farming_app', '0008_alter_farmercomplain_model_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 27, 19, 54, 3, 971637))),
                ('subject', models.CharField(max_length=50)),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='farmercomplain_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 27, 19, 54, 3, 970565)),
        ),
        migrations.AlterField(
            model_name='farmertips_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 27, 19, 54, 3, 971637)),
        ),
        migrations.AlterField(
            model_name='retailer_model',
            name='confirmation',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='retailer_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 27, 19, 54, 3, 970565)),
        ),
        migrations.AlterField(
            model_name='signup_model',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 27, 19, 54, 3, 970565)),
        ),
    ]
